service1:
  port: 8081
  name: service1
  newBookChannelName: "new_book"
  dbConnectionString: "host=localhost user=user password=1234 dbname=library port=5432 sslmode=disable"
service2:
  port: 8082
  name: test2
  newBookChannelName: "new_book"
  dbConnectionString: "host=localhost user=user password=1234 dbname=library port=5432 sslmode=disable"
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
