service1:
  port: 8081
  name: service1
  newBookChannelName: "new_book"
service2:
  port: 8082
  name: test2
  newBookChannelName: "new_book"
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
