service1:
  port: 8081
  name: service1
  newBookChannelName: "new_book"
  dbConnectionString: "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable"
service2:
  port: 8082
  name: test2
  newBookChannelName: "new_book"
  dbConnectionString: "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable"
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
